#!/bin/sh
# Writes js/config.js from the API_BASE setting. Runs automatically on every Vercel build (see vercel.json).
#
# Where API_BASE comes from, first match wins:
#   1. the environment — e.g. Vercel → Project → Settings → Environment Variables → API_BASE
#   2. the env file given as the first argument, or .env next to this script (local use)
# On Vercel the build fails if API_BASE is missing or isn't an https:// URL, so a deploy can
# never go out pointing at localhost or nowhere.
set -e
cd "$(dirname "$0")"
ENV_FILE="${1:-.env}"
SOURCE="environment"
if [ -z "${API_BASE+x}" ]; then
  if [ -f "$ENV_FILE" ]; then
    API_BASE=$(grep -E '^API_BASE=' "$ENV_FILE" | tail -1 | cut -d= -f2- | sed 's/[[:space:]]#.*$//' | tr -d '"'"'"'\r ')
    SOURCE="$ENV_FILE"
  else
    API_BASE=""; SOURCE="(not set)"
  fi
fi
API_BASE=$(printf '%s' "$API_BASE" | tr -d '\r ' | sed 's#/*$##')   # trim spaces and trailing slashes

fail() { echo "config-from-env: $1" >&2; exit 1; }
case "$API_BASE" in
  ""|http://*|https://*) ;;
  *) fail "API_BASE must start with https:// (got '$API_BASE' from $SOURCE)" ;;
esac
case "$API_BASE" in *"'"*|*'"'*|*'<'*|*'>'*|*'\\'*) fail "API_BASE contains characters that aren't allowed in a URL" ;; esac
if [ -n "$VERCEL" ]; then
  [ -n "$API_BASE" ] || fail "API_BASE is not set. Add it in Vercel → Project → Settings → Environment Variables (e.g. https://api.thulori.com), then redeploy."
  case "$API_BASE" in https://*) ;; *) fail "API_BASE must be an https:// URL on Vercel (got '$API_BASE')" ;; esac
  case "$API_BASE" in *localhost*|*127.0.0.1*) fail "API_BASE points at localhost ($API_BASE) — set the real API URL in Vercel" ;; esac
fi

cat > js/config.js <<JS
/* Generated by config-from-env.sh from API_BASE ($SOURCE) — don't edit by hand.
   apiBase: the Thulori API (the server app). */
window.THULORI_ADMIN = {
  apiBase: '$API_BASE'
};
JS
echo "config-from-env: js/config.js → apiBase '$API_BASE' (from $SOURCE)"
